imports:
    - { resource: "@MirschAdminBundle/Resources/config/app/security.yml" }

security:

    providers:
        adminuser:
            entity:
                class: AppBundle:AdminUser
                # we have to unset the property so loadUserByUsername() in the repository is used
                property: ~

    encoders:
        AppBundle\Entity\AdminUser: bcrypt
