# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#parameters:
#    parameter_name: value

services:
    mirsch.admin.form.admin_user_type:
        class: AppBundle\Form\AdminUserType
        arguments: ['%mirsch.admin.model.admin_user.entity%', '%mirsch.admin.model.admin_group.entity%']
        tags:
            - { name: form.type }
