header: |
    opencaching.de
      ___  _ __   ___ _ __   ___ __ _  ___| |__ (_)_ __   __ _
     / _ \| '_ \ / _ \ '_ \ / __/ _` |/ __| '_ \| | '_ \ / _` |
    | (_) | |_) |  __/ | | | (_| (_| | (__| | | | | | | | (_| |
     \___/| .__/ \___|_| |_|\___\__,_|\___|_| |_|_|_| |_|\__, |
          |_|                                            |___/


paths:
  - dev-ops/local.team-opencaching.de/actions

