language: php
php:
  - 7.2
  - 7.3
sudo: required
dist: xenial

before_script:
  - docker-compose up -d --build
  - sudo chmod +x build/travis-ci.sh psh.phar

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

before_install:
  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
    - build/travis-ci.sh
    - ./psh.phar travis-ci:init-docker

script:
    - ./psh.phar travis-ci:code-style
    - ./psh.phar travis-ci:unit

after_script:
  - docker-compose down

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - git reset --hard
    - git clean -fd

matrix:
  allow_failures:
    - php: 7.3

deploy:
  provider: script
  script: bin/upload-crowdin.sh
  on:
    branch: development
