version: "3.1"
services:
    mailhog:
        image: mailhog/mailhog:latest
        container_name: opencaching-mailhog
        ports:
            - "8025:8025"

    mariadb:
        image: mariadb:10.1
        container_name: opencaching-mariadb
        working_dir: /application
        volumes:
            - .:/application
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=opencaching
            - MYSQL_USER=opencaching
            - MYSQL_PASSWORD=opencaching
        ports:
            - "3306:3306"

    webserver:
        image: nginx:alpine
        container_name: opencaching-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    php-fpm:
        build: docker/php-fpm
        container_name: opencaching-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
