# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

imports:
    - { resource: services_oc.yml }

services:
    app.token_legacy_authenticator:
        class: AppBundle\Legacy\Security\LegacyAuthenticator

    app.form.upload_field_note:
        class: AppBundle\Form\UploadFieldNotesType
        arguments: ['@translator']
        tags:
            - { name: form.type }

    app.service.field_note:
        class: AppBundle\Service\FieldNoteService
        arguments: ['@doctrine.orm.default_entity_manager', '@translator']

    app.dataprovider.upload_field_note:
        class: AppBundle\Form\DataProvider\UploadFieldNotesDataProvider
        arguments: ['@app.service.field_note']

    app.controller.changelog_controller:
        class: AppBundle\Controller\ChangelogController
        arguments: ['@app.library.common_mark_converter', '@twig']

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
