services:
    app.library.common_mark_converter:
        class: League\CommonMark\CommonMarkConverter

    oc.util.dbal_connection:
            class: Oc\Util\DbalConnection
    oc_bundle.postfix.journal_logs:
        class: Oc\Postfix\JournalLogs
        arguments: ['@app.dbal_connection']
    oc.translation.crowdin_import:
        class: Oc\Translation\CrowdinImport
        arguments: ['@app.dbal_connection']
    oc.geo_cache.reports:
        class: Oc\GeoCache\Reports
        arguments: ['@app.dbal_connection']
    app.dbal_connection:
        class: Doctrine\DBAL\Connection
        factory: ['Oc\Util\DbalConnection', createDbalConnection]
        arguments: ["%database_host%", "%database_name%", "%database_user%", "%database_password%", "%database_port%"]
