# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.token_legacy_authenticator:
        class: AppBundle\Legacy\Security\LegacyAuthenticator

    app.form.upload_field_note:
        class: AppBundle\Form\UploadFieldNotesType
        arguments: ['@translator']
        tags:
            - { name: form.type }

    app.service.field_note:
        class: AppBundle\Service\FieldNoteService
        arguments: ['@doctrine.orm.default_entity_manager', '@translator']

    app.dataprovider.upload_field_note:
        class: AppBundle\Form\DataProvider\UploadFieldNotesDataProvider
        arguments: ['@app.service.field_note']

    app.controller.changelog_controller:
        class: AppBundle\Controller\ChangelogController
        arguments: ['@app.library.common_mark_converter', '@twig']

    app.library.common_mark_converter:
        class: League\CommonMark\CommonMarkConverter

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    oc.util.dbal_connection:
        class: Oc\Util\DbalConnection
    oc_bundle.postfix.journal_logs:
        class: Oc\Postfix\JournalLogs
        arguments: ['@app.dbal_connection']
    oc.translation.crowdin_import:
        class: Oc\Translation\CrowdinImport
        arguments: ['@app.dbal_connection']
    oc.geo_cache.reports:
        class: Oc\GeoCache\Reports
        arguments: ['@app.dbal_connection']
    app.dbal_connection:
        class: Doctrine\DBAL\Connection
        factory: ['Oc\Util\DbalConnection', createDbalConnection]
        arguments: [%database_host%, %database_name%, %database_user%, %database_password%, %database_port%]
